name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Meson and Ninja
      run: sudo apt update && sudo apt install -y meson ninja-build

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -S ${{github.workspace}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/build/INSTALLDIR

    - name: Build and test
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --parallel
